name: Rust CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  fmt:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v7
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - run: cargo fmt --all --check

  tests:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v7
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy
      - run: cargo test --workspace --all-targets --all-features

  clippy:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v7
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy
      - name: clippy normal
        run: cargo clippy --workspace --all-targets --all-features

  pedantic:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v7
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy
      - name: clippy pedantic
        run: cargo clippy --workspace --all-targets --all-features -- -W clippy::pedantic
        env:
          RUSTFLAGS: ""
